
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234


development:
  <<: *default
  database: sistema_visitas_development

test:
  <<: *default
  database: sistema_visitas_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    host: db
    database: sistema_visitas_production
    username: postgres
    password: 1234
  cache:
    <<: *primary_production
    database: sistema_visitas_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sistema_visitas_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sistema_visitas_production_cable
    migrations_paths: db/cable_migrate